name: interestin_event_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.17.5  
  provider: ^6.1.2
  uuid: ^4.5.1
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  
  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Event Specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/
    - assets/icons/categories/
    - assets/fonts/
  
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
    - family: Chapaza
      fonts:
        - asset: assets/fonts/Chapaza-Italic.ttf
          weight: 400
        - asset: assets/fonts/Chapaza.ttf
          weight: 700